### ISSUE TITLE
players[data.USN].offline is not a function

### ISSUE THREAD

**Issue by Evinyatar** [Evinyatar/pith#32]
```
TypeError: players[data.USN].offline is not a function
    at EventEmitter.client.subscribe.on.on.on (/home/christoph/workspace/pith/plugins/upnp-mediarenderer/plugin.js:308:39)
    at EventEmitter.emit (events.js:189:13)
    at /home/christoph/workspace/pith/lib/ssdp.js:52:29
    at Socket.<anonymous> (/home/christoph/workspace/pith/lib/ssdp.js:35:17)
    at Socket.emit (events.js:189:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
```

Player sends `byebye` before initialization is complete causing it to call `offline` on the placeholder object instead.

**Comment by Evinyatar** [comment]
Fixed in ed3d02753da5e7b31385919870e3e9870a484299
